package us.dit.consentimientos.model;

	/**
	 * This class was automatically generated by the data modeler tool.
	 */

	public class Mensaje implements java.io.Serializable {

		static final long serialVersionUID = 1L;

		
		private java.lang.String remitente;
		
		private java.lang.String url;
		
		private java.lang.Integer medida;
		
		private java.lang.String tipo;

		public Mensaje() {
		}

		public java.lang.String getRemitente() {
			return this.remitente;
		}

		public void setRemitente(java.lang.String remitente) {
			this.remitente = remitente;
		}

		public java.lang.String getUrl() {
			return this.url;
		}

		public void setUrl(java.lang.String url) {
			this.url = url;
		}

		public java.lang.Integer getMedida() {
			return this.medida;
		}

		public void setMedida(java.lang.Integer medida) {
			this.medida = medida;
		}

		public java.lang.String getTipo() {
			return this.tipo;
		}

		public void setTipo(java.lang.String tipo) {
			this.tipo = tipo;
		}

		public Mensaje(java.lang.String remitente, java.lang.String url,
				java.lang.Integer medida, java.lang.String tipo) {
			this.remitente = remitente;
			this.url = url;
			this.medida = medida;
			this.tipo = tipo;
		}
		
		@Override
		public String toString(){
		    String mensaje="Mensaje de: "+this.remitente+" tipo "+this.tipo+" medida "+this.medida+" y url "+this.url;
		    return mensaje;
		}

	}